Repository Team-CDJJ/BANDIN, pull requests merged in 2022-12, with the labels that each got.

#2 feat: 로그인 페이지 마크업
  .eslintrc.js
  src/App.jsx
  src/assets/404.png
  src/assets/facebook.png
  src/assets/google.png
  src/assets/kakao.png
  src/assets/logo-white.png
  src/assets/logo.png
  src/assets/profile.png
  src/components/atoms/Button/Button.jsx
  src/pages/EmailLogin/EmailLogin.jsx
  src/pages/EmailLogin/styled.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/styled.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/styled.jsx
  src/styles/Globalstyled.jsx
Labels: FEAT

#4 feat: 스플래쉬 페이지 임시 구현
  .eslintrc.js
  src/App.jsx
  src/index.jsx
  src/pages/EmailLogin/styled.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/styled.jsx
  src/pages/SignUp/styled.jsx
  src/pages/Splash/Splash.jsx
  src/pages/Splash/styled.jsx
  src/styles/theme.js
Labels: FEAT

#10 Feat/로그인 페이지
  .eslintrc.js
  package-lock.json
  package.json
  src/App.jsx
  src/api/api.js
  src/api/login/postSignUP.js
  src/api/login/postUserLogin.js
  src/assets/logo-txt-white.png
  src/assets/logo-txt.png
  src/components/atoms/Button/Button.jsx
  src/components/atoms/Button/styled.jsx
  src/components/atoms/Input/Input.jsx
  src/components/atoms/InputLabel/InputLabel.jsx
  src/pages/EmailLogin/EmailLogin copy.jsx
  src/pages/EmailLogin/EmailLogin.jsx
  src/pages/EmailLogin/styled.jsx
  src/pages/Login/Login.jsx
  src/pages/SetUpProfile/SetUpProfile.jsx
  src/pages/SetUpProfile/styled.jsx
  src/pages/SignUp/SignUp.jsx
  src/pages/SignUp/styled.jsx
  src/styles/Globalstyled.jsx
Labels: FEAT

#8 Feat/유저UI
  src/App.jsx
  src/assets/icon- more-vertical.png
  src/assets/icon-arrow-left.png
  src/assets/icon-edit.png
  src/assets/icon-heart.png
  src/assets/icon-home.png
  src/assets/icon-message-circle.png
  src/assets/icon-search.png
  src/assets/icon-user.png
  src/components/Button/Button_Yunjeong.jsx
  src/components/Button/styled.jsx
  src/components/CommonUI/CommonPost/CommonPost.jsx
  src/components/CommonUI/CommonPost/styled.jsx
  src/components/CommonUI/DeleteAlert/DeleteAlert.jsx
  src/components/CommonUI/DeleteAlert/styled.jsx
  src/components/CommonUI/UserItem/UserItem.jsx
  src/components/CommonUI/UserItem/styled.jsx
  src/pages/Following/Following.jsx
  src/pages/Following/styled.jsx
Labels: FEAT

#6 FEAT / 공통 바 마크업
  src/App.jsx
  src/assets/icon-more-vertical.png
  src/components/Button/Button.jsx
  src/components/CommonUI/Comment/Comment.jsx
  src/components/CommonUI/Comment/styled.jsx
  src/components/CommonUI/DeleteAlert/DeleteAlert.jsx
  src/components/CommonUI/Nav/TopBasicNav/TopBasicNav.jsx
  src/components/CommonUI/Nav/TopBasicNav/styled.jsx
  src/components/CommonUI/Nav/TopChatNav/TopChatNav.jsx
  src/components/CommonUI/Nav/TopChatNav/styled.jsx
  src/components/CommonUI/Nav/TopMainNav/TopMainNav.jsx
  src/components/CommonUI/Nav/TopMainNav/styled.jsx
  src/components/CommonUI/Nav/TopSearchNav/TopSearchNav.jsx
  src/components/CommonUI/Nav/TopSearchNav/styled.jsx
  src/components/CommonUI/Nav/TopUploadNav/TopUploadNav.jsx
  src/components/CommonUI/Nav/TopUploadNav/styled.jsx
  src/components/CommonUI/TabMenu/TabMenu.jsx
  src/components/CommonUI/TabMenu/styled.jsx
Labels: FEAT

#13 feat: 404페이지 마크업 및 디자인
  src/pages/404/404.jsx
  src/pages/404/styled.jsx
Labels: FEAT

#20 feat: 검색페이지 마크업 및 디자인
  src/pages/Search/Search.jsx
  src/pages/Search/styled.jsx
Labels: FEAT

#24 Feat/매칭 페이지
  package-lock.json
  src/App.jsx
  src/assets/post.png
  src/components/CommonUI/CommonOnlyText/CommonOnlyText.jsx
  src/components/CommonUI/Nav/TopMainNav/styled.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/styled.jsx
Labels: FEAT

#27 feat: CommonUI 전반적 수정
  src/assets/icon-home-fill.png
  src/assets/icon-message-circle-fill.png
  src/components/CommonUI/Comment/Comment.jsx
  src/components/CommonUI/Comment/styled.jsx
  src/components/CommonUI/Nav/TopBasicNav/styled.jsx
  src/components/CommonUI/Nav/TopChatNav/TopChatNav.jsx
  src/components/CommonUI/Nav/TopChatNav/styled.jsx
  src/components/CommonUI/Nav/TopMainNav/TopMainNav.jsx
  src/components/CommonUI/Nav/TopMainNav/styled.jsx
  src/components/CommonUI/Nav/TopSearchNav/TopSearchNav.jsx
  src/components/CommonUI/Nav/TopSearchNav/styled.jsx
  src/components/CommonUI/Nav/TopUploadNav/TopUploadNav.jsx
  src/components/CommonUI/Nav/TopUploadNav/styled.jsx
  src/components/CommonUI/TabMenu/TabMenu.jsx
  src/components/CommonUI/TabMenu/styled.jsx
  src/pages/Follower/Follower.jsx
  src/pages/Following/Following.jsx
Labels: FEAT

#29 feat: 상품등록 페이지 마크업 및 검색계정 페이지 스타일링
  src/assets/img-button.png
  src/components/modules/AddProductInput/AddProductInput.jsx
  src/components/modules/AddProductInput/styled.jsx
  src/pages/AddProduct/AddProduct.jsx
  src/pages/AddProduct/styled.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/styled.jsx
Labels: FEAT

#30 feat: 드롭다운
  src/assets/down-arrow.png
  src/assets/up-arrow.png
  src/components/CommonUI/DropDown/DropDown.jsx
  src/components/CommonUI/DropDown/styled.jsx
  src/components/CommonUI/Nav/TopMainNav/TopMainNav.jsx
  src/components/CommonUI/Nav/TopMainNav/styled.jsx
Labels: FEAT

#32 feat: 프로필수정 페이지 마크업 및 디자인
  src/pages/ModifyProfile/ModifyProfile.jsx
  src/pages/ModifyProfile/styled.jsx
Labels: FEAT

#33 feat: 전체width조절, 색,배경 변경, 그외 숫자 조정
  src/components/CommonUI/DropDown/DropDown.jsx
  src/components/CommonUI/DropDown/styled.jsx
  src/components/CommonUI/Nav/TopMainNav/TopMainNav.jsx
  src/components/CommonUI/Nav/TopMainNav/styled.jsx
  src/components/CommonUI/Nav/TopUploadNav/TopUploadNav.jsx
  src/components/CommonUI/Nav/TopUploadNav/styled.jsx
Labels: enhancement

#36 feat: 이전페이지 이동 기능 구현
  src/pages/404/404.jsx
  src/pages/404/styled.jsx
Labels: FEAT

#37 feat: 채팅방페이지, 모달창, Comment폴더, 사진 추가
  src/assets/dog.png
  src/components/CommonUI/Comment/Comment.jsx
  src/components/CommonUI/Comment/styled.jsx
  src/components/CommonUI/PostModal/PostModal.jsx
  src/components/CommonUI/PostModal/styled.jsx
  src/pages/ChatRoom/ChatRoom.jsx
  src/pages/ChatRoom/styled.jsx
Labels: FEAT

#41 feat: 계정검색 기능 구현
  src/api/searchuser/searchuser.js
  src/components/CommonUI/Nav/TopSearchNav/TopSearchNav.jsx
  src/components/CommonUI/UserItem/UserItem.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/styled.jsx
Labels: FEAT

#42 feat/재사용성_수정(더 필요)
  src/components/CommonUI/Comment/Comment.jsx
  src/components/CommonUI/Comment/styled.jsx
  src/components/CommonUI/CommonPost/styled.jsx
  src/components/CommonUI/DeleteAlert/DeleteAlert.jsx
  src/components/CommonUI/Nav/TopBasicNav/TopBasicNav.jsx
  src/components/CommonUI/Nav/TopBasicNav/styled.jsx
  src/components/CommonUI/Nav/TopChatNav/TopChatNav.jsx
  src/components/CommonUI/Nav/TopChatNav/styled.jsx
  src/components/CommonUI/Nav/TopMainNav/TopMainNav.jsx
  src/components/CommonUI/Nav/TopMainNav/styled.jsx
  src/components/CommonUI/Nav/TopSearchNav/TopSearchNav.jsx
  src/components/CommonUI/Nav/TopSearchNav/styled.jsx
  src/components/CommonUI/Nav/TopUploadNav/TopUploadNav.jsx
  src/components/CommonUI/Nav/TopUploadNav/styled.jsx
  src/components/CommonUI/PostModal/PostModal.jsx
  src/components/CommonUI/PostModal/styled.jsx
  src/components/CommonUI/TabMenu/TabMenu.jsx
  src/pages/ChatList/ChatList.jsx
  src/pages/ChatRoom/ChatRoom.jsx
  src/pages/ChatRoom/styled.jsx
  src/pages/Follower/Follower.jsx
  src/pages/Following/Following.jsx
  src/pages/Home/Home.jsx
Labels: enhancement

#47 feat: 상품등록 기능 구현
  src/api/addproduct/addproduct.js
  src/atoms.js
  src/components/CommonUI/Nav/TopUploadNav/TopUploadNav.jsx
  src/components/modules/AddProductInput/AddProductInput.jsx
  src/components/modules/AddProductInput/styled.jsx
  src/components/modules/ProductImgInput/ProductImgInput.jsx
  src/components/modules/ProductImgInput/styled.jsx
  src/pages/AddProduct/AddProduct.jsx
Labels: FEAT

#53 feat: follow 목록
  src/api/profile/follow.js
  src/api/profile/getfollower.js
  src/api/profile/getfollowing.js
  src/components/modules/Profile/ProfileInfo.jsx
  src/components/modules/YourProfileBtn/YourProfileBtn.jsx
  src/pages/Follower/Follower.jsx
  src/pages/Following/Following.jsx
Labels: FEAT

#56 Feat/프로필수정 기능
  src/api/modifyprofile/modifyprofile.js
  src/pages/ModifyProfile/ModifyProfile.jsx
  src/pages/ModifyProfile/styled.jsx
Labels: FEAT

#58 Feat/프로필 게시글 페이지
  src/api/GETprofilepost/GETprofilepost.js
  src/api/getProductList/getProducList.js
  src/assets/icon-post-album-off.png
  src/assets/icon-post-album-on.png
  src/assets/icon-post-list-off.png
  src/assets/icon-post-list-on.png
  src/components/CommonUI/CommonProduct/CommonProduct.jsx
  src/components/CommonUI/CommonProduct/styled.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/pages/ProfilePost/ProfilePost.jsx
  src/pages/ProfilePost/styled.jsx
Labels: FEAT

#64 Feat/프로필 게시글 구현 완료
  package-lock.json
  package.json
  src/api/getProfilePost/getProfilePost.js
  src/components/CommonUI/CommonPost/CommonPost.jsx
  src/components/CommonUI/CommonPost/styled.jsx
  src/components/CommonUI/CommonProduct/styled.jsx
  src/components/modules/Profile/styled.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/pages/ProfilePost/ProfilePost.jsx
  src/pages/ProfilePost/styled.jsx
Labels: FEAT

#63 feat: 좋아요 기능 구현 완료
  src/api/LikeAxios/LikeAxios.js
  src/components/CommonUI/CommonPost/CommonPost.jsx
  src/components/modules/LikeBtn/LikeBtn.jsx
  src/components/modules/LikeBtn/styled.jsx
Labels: FEAT

#61 feat: 상품수정 기능 구현
  src/App.jsx
  src/api/modifyProduct/deleteProductData.js
  src/api/modifyProduct/getProductData.js
  src/api/modifyProduct/putModifiedData.js
  src/components/CommonUI/CommonProduct/CommonProduct.jsx
  src/components/CommonUI/DeleteAlert/DeleteAlert.jsx
  src/components/CommonUI/DeleteAlert/styled.jsx
  src/components/CommonUI/ProductModal/ProductModal.jsx
  src/components/CommonUI/ProductModal/styled.jsx
  src/pages/AddProduct/AddProduct.jsx
  src/pages/ModifyProduct/ModifyProduct.jsx
  src/pages/ModifyProduct/styled.jsx
Labels: FEAT

#66 Feat/다른사람 계정에서 목록
  src/pages/Follower/Follower.jsx
  src/pages/Following/Following.jsx
Labels: enhancement, FEAT

#67 Feat/게시글 댓글
  src/api/comment/deleteComment.js
  src/api/comment/reportComment.js
  src/api/post/postComments.js
  src/components/CommonUI/Comment/Comment.jsx
  src/components/CommonUI/CommonPost/CommonPost.jsx
  src/components/CommonUI/PostModal/PostModal.jsx
  src/components/CommonUI/PostModal/styled.jsx
  src/components/modules/PostComment/PostComment.jsx
  src/components/modules/PostComment/styled.jsx
  src/components/modules/TimeAgo/TimeAgo.jsx
  src/pages/ChatRoom/ChatRoom.jsx
  src/pages/PostDetail/PostDetail.jsx
Labels: enhancement, FEAT

#75 feat: 다른 계정의 팔로워, 팔로잉에서 이상하게 보이는 내 계정 버튼 없애기
  src/pages/Follower/Follower.jsx
  src/pages/Following/Following.jsx
Labels: enhancement, FEAT

#72 Feat/프로필 모달 구현
  src/components/CommonUI/Nav/TopBasicNav/TopBasicNav.jsx
  src/components/CommonUI/Nav/TopMainNav/styled.jsx
  src/components/CommonUI/PostModal/PostModal.jsx
  src/components/CommonUI/PostModal/styled.jsx
  src/components/CommonUI/ProductModal/ProductModal.jsx
  src/components/modules/PostUserInfo/PostUserInfo.jsx
  src/components/modules/Profile/ProfileInfo.jsx
Labels: FEAT
