Repository Team-CDJJ/BANDIN, pull requests merged in 2023-01, with the labels that each got.

#79 design: followers,following 상단 글씨 보이도록 수정
  src/pages/Follower/styled.jsx
  src/pages/Following/styled.jsx
Labels: STYLE

#82 feat: 게시글에도 시간 어느 정도 지났는지 표시
  src/components/CommonUI/CommonPost/CommonPost.jsx
  src/components/modules/PostUserInfo/PostUserInfo.jsx
  src/components/modules/PostUserInfo/styled.jsx
Labels: enhancement, FEAT

#88 fix: 프로필 이미지 변경 오류 수정
  src/pages/ModifyProfile/ModifyProfile.jsx
Labels: BUG

#87 faet: 최상단 버튼 추가
  src/assets/top-btn.png
  src/pages/Home/Home.jsx
  src/pages/Home/styled.jsx
Labels: FEAT

#86 feat: 댓글 삭제 혹은 신고 확인하는 알림창
  src/components/modal/CommentModal/CommentAlert.jsx
  src/components/modal/CommentModal/CommentModal.jsx
  src/components/modules/PostComment/PostComment.jsx
Labels: enhancement, FEAT

#90 feat: scroll에 behavior smooth 추가하여 움직임 부드럽게
  src/pages/Home/Home.jsx
Labels: enhancement, FEAT

#92 Feat/로딩화면
  src/pages/Home/Home.jsx
  src/pages/Home/styled.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/pages/MyProfile/styled.jsx
Labels: FEAT
